name: indefinite_progress_indicator
description: A new Flutter package.
version: 1.0.0
author: Tomislav Novoselec
homepage: https://github.com/tnovoselec/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: